version: 2.1

orbs:
  docker: circleci/docker@0.5.13
  aws-ecr: circleci/aws-ecr@6.2.0

workflows:
  build-container-1:
    - docker/publish:
        path: container-1
        deploy: false
        image: $CIRCLE_PROJECT_USERNAME/${CIRCLE_PROJECT_REPONAME}-container-1
  build-container-2:
    - docker/publish:
        deploy: false
        path: container-2
        image: $CIRCLE_PROJECT_USERNAME/${CIRCLE_PROJECT_REPONAME}-container-2
