version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.2.0

workflows:
  build-container-1:
    jobs:
      - aws-ecr/build-image:
          create-repo: true
          path: container-1
          repo: myECRRepository-1
  build-container-2:
    jobs:
      - aws-ecr/build-image:
          create-repo: true
          path: container-2
          repo: myECRRepository-2
